tmpPath: '/var/tmp/backer'
defaultTarget: 'local'
socketPath: '/var/run/docker.sock'
logLevel: 'info'
api:
  web: false
  socket: false
targets:
- name: 'default'
  type: 'local'
  dir: '/var/opt/backer/local'
  default: true
middlewares: []
mandates: {}
