api:
  web: true
  socket: true
logLevel: 'debug'
targets:
- name: 'default'
  type: 'local'
  dir: '/var/opt/backer/local'
  default: true
- name: 'minio'
  type: 's3'
  bucket: 'test'
  s3Client:
    endpoint: 'http://minio:9000'
    accessKeyId: 'minio'
    secretAccessKey: 'minio123'
    s3ForcePathStyle: true
middlewares:
- name: 'compression'
  type: 'gzip'
- name: 'encryption'
  type: 'ccrypt'
  key: '1234'
mandates:
  test_mariadb_static_1:
    labels:
      type: 'mysql'
      interval: '* * * * *'
      network: 'test_default'
      mysql:
        user: 'Text:root'
        password: 'Env:MYSQL_ROOT_PASSWORD'
        database: 'Env:MYSQL_DATABASE'
      target: 'minio'
      middleware: 'compression,encryption'
